---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: swagger
spec:
  stripPrefix:
    prefixes:
      - /swagger-ui

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: swagger
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/swagger-ui`)
      kind: Rule
      services:
        - name: swagger
          port: http
      middlewares:
        - name: swagger
