apiVersion: v1
kind: Service
metadata:
  name: swagger
  labels:
    app.kubernetes.io/name: swagger
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: swagger
